### ISSUE TITLE
Test with coverage disabled

### ISSUE THREAD

**Issue by Bogala** [flutter/flutter-intellij#7810]
Hello,

I can't launch Tests with Coverage since my last plugin update : 
- the option is not available
- when I add manually shortcut tu Run "Tests in test" with coverage, the button is disabled
![image](https://github.com/user-attachments/assets/732c3efb-0922-4662-89d4-35b2dfb35b26)

## Steps to Reproduce

I have tried :
- File | Invalidate Caches | Invalidate and Restart
- steps suggested by File | Repair IDE
- Manually re-generate project configuration settings
- Reinstall plugins
- Reinstall IDE (IntelliJ IDEA Ultimate
- With other IDE (Android Studio)

### Flutter Doctor

Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-FR)
    • Flutter version 3.24.5 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

IntelliJ IDEA Ultimate Edition (version 2024.3)
    • IntelliJ at /Users/bfontaine/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 82.2.4
    • Dart plugin version 243.22562.3

### IDE Configuration

IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 13, 2024
Licensed to Benoit FONTAINE
Subscription is active until December 6, 2024.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  suggest.all.run.configurations.from.context=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.apacheConfig (243.21565.208)
  PythonCore (243.21565.211)
  com.jetbrains.rust (243.21565.245)
  name.kropp.intellij.makefile (243.21565.122)
  com.github.bufbuild.intellij (0.4.1)
  org.jetbrains.plugins.go (243.21565.211)
  com.jetbrains.space (243.21565.122)
  Pythonid (243.21565.211)
  com.intellij.mermaid (0.0.24+IJ.243)
  gherkin (243.21565.122)
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  Dart (243.22562.3)
  pl.pszklarska.pubversionchecker (1.3.5)
  org.jetbrains.android (243.21565.214)
  com.android.tools.design (243.21565.214)
  com.intellij.tide (243.21565.245)
  io.flutter (82.2.4)
  mobi.hsz.idea.gitignore (4.5.4)
  com.jetbrains.php (243.21565.211)
  izhangzhihao.rainbow.brackets (2024.2.7-241)
  com.github.copilot (1.5.29.7524)
Kotlin: 243.21565.193-IJ

**Comment by AntoineMaille** [comment]
Hello,

Same problem here

**Comment by doctor-g** [comment]
I may have encountered the same problem and have been able to come up with a simple reproduction of it:

1. Create a new Flutter project. Notice that `widget_test.dart` can be run with coverage by right-clicking on it.
2. Add Dart's test library via `flutter pub add dev:test`. Running with coverage is no longer available.

**Comment by jwren** [comment]
Context: When the Flutter IJ was updated to use the required IntelliJ Platform Gradle Plugin version 2.1.0, see https://github.com/flutter/flutter-intellij/pull/7774, the coverage code refused to build, it was removed at that time.  It is my intention to get it working again.

**Comment by jwren** [comment]
Update here, for just the `2023.3` build (AS Meerkat) version of the plugin, the dependencies aren't resolvable.  Normal methods haven't yielded a solution yet:

1. I am compiling against the most recent AS canary
2. The files have not been modified in intellij-community
3. Other plugins haven't made any changes, having a dependency on `com.intellij.modules.coverage` in the `plugin.xml` is still sufficient for other plugins.

Example of the error being produced by 
```
    symbol:   class ProjectData
    location: class FlutterCoverageRunner
  /usr/local/google/home/jwren/src/flutter-intellij/flutter-idea/src/io/flutter/run/coverage/FlutterCoverageRunner.java:35: error: cannot find symbol
      final ProjectData projectData = new ProjectData();
```

**Comment by rydmike** [comment]
Thanks @jwren for you efforts in getting this to work again. I'm really hit by this, I have tried several other in editor and external code coverage test display/analysis tools, but nothing comes close to the convenience IntelliJ has on this front.

I even tried using VS-Code, but I could not get the extension "Coverage Gutters" that is supposed to do something similar there, to work either, it just does nothing when I tried.

Currently I have 3 pub package updates on hold, since I can't analyze my test coverage with any sensible tool that I'm used too and with decent DX, before I publish them.

Still looking for some alternative tool that would work even temporarily.

**Comment by jwren** [comment]
@rydmike Thanks for this context.  I continued to try more today to get these sources compiling.  I have them working on 2023.3, 2024.1 and 2024.2 IDEA and Android Studio APIs.  However, for AS 2024.3 (Meerkat), the coverage dependency is not being pulled in as it is for the other platform versions.  Attempts to upgrade to newer Gradle, Java, Kotlin and IJ Gradle versions for 2024.3 has been my most recent attempt at resolving this, but I have not had any luck yet to date.

When teams get back from vacation both at JetBrains and Google next week, I will reach out.

**Comment by iPypeNB** [comment]
Hi @rydmike, do you have any news on this topic? I am also affected by the fact that I no longer have this tool.

**Comment by rydmike** [comment]
It is @jwren that is working on it that would know, I'm just affected by it like you 😃 Seems to be a tricky case though, I hope it gets resolved soon as well.

**Comment by jwren** [comment]
Current status here, the IntelliJ Gradle version used to build the Flutter IJ product is not able to resolve the dependencies, my current hypothesis is that this is from the upstream changes https://github.com/search?q=org%3AJetBrains+IJPL-156066&type=commits in the IDEA framework.  I have emails out to appropriate individuals who may have additional insights in how to resolve this for the Flutter plugin.

**Comment by jwren** [comment]
The fix here is to include 

```
      bundledModule("intellij.platform.coverage")
      bundledModule("intellij.platform.coverage.agent")
```

for Meerkat + versions.  I was also informed that by upgrading `org.jetbrains.intellij.platform` to `2.2.1` will resolve this new requirement.

**Comment by MarauderOne** [comment]
Apologies if I have missed something here, but what is the fix for Android Studio?

**Comment by jwren** [comment]
This issue was closed when I landed the PR that I was told would fix it, however I am troubleshooting other issues with the release, hence M84 is not out yet. (https://plugins.jetbrains.com/plugin/9212-flutter/edit/versions).

**Comment by jwren** [comment]
The instructions to include

```
      bundledModule("intellij.platform.coverage")
      bundledModule("intellij.platform.coverage.agent")
```

pre `org.jetbrains.intellij.platform` upgrade to `2.2.1`, https://github.com/flutter/flutter-intellij/issues/7936, completely put Android Studio 2024.2 (Ladybug) and Android Studio 2024.3 (Meerkat) into a **locked state**.

The fix has been reverted with https://github.com/flutter/flutter-intellij/pull/7937

**Comment by AntoineMaille** [comment]
Since today i cant even execute tests although i did not update flutter intellij. I Get no tests found although flutter test command works

**Comment by tcf909** [comment]
Did this ever get resolved?

I downgraded to 2024.2.5 and tried both the stable and dev versions of the flutter intellij plugin.

Still not able to run tests with coverage.

**Comment by marcellocamara** [comment]
> Still not able to run tests with coverage.

@tcf909 you should downgrade you flutter plugin to lower than 82.2

See this changelog:

![Image](https://github.com/user-attachments/assets/d64061b8-6c96-4ca3-9c4f-0086ff76c2c3)

**Comment by rydmike** [comment]
It is very unfortunate that work on this seems to be stuck or abandoned. Concluding that since it has been 4 months since it was reported.

I tried numerous extensions on VS-Code to find something that would even come close to how well this used to work on IJ, but nothing works as well on VS-Code or at all, and if it sort of does, it does not come close to how well this used to work. Does anybody have anything similar that works well on VS-Code?

Hopefully this issue can be fixed and functionality restored.

**Comment by marcellocamara** [comment]
This issue is a bit of a headache, since it no longer allows you to update the IDE to new versions...
Plugin lower than 82.2 cannot be installed in new versions of IDEs.

![Image](https://github.com/user-attachments/assets/6a929a97-fcf5-4b1f-8807-5a79437fc333)

Is there a light at the end of the tunnel? Months without fix :(

**Comment by jwren** [comment]
Fixed with the PR that just landed

<img width="298" alt="Image" src="https://github.com/user-attachments/assets/5f78395a-f695-4355-ae3e-2426c3a7337a" />

**Comment by rydmike** [comment]
Thank you, awesome work and much appreciated 🙏🏻❤️
